#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive
if command -v apt &> /dev/null; then
    sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" --plugin dotbot-apt-get/aptget.py -d "${BASEDIR}" --config-file packages.yaml
    # Set the shell 
    if ! [[ $SHELL = "/usr/bin/fish" ]]; then
        sudo chsh -s /usr/bin/fish
    fi
fi
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
